% f=imread('C:\Users\Marjan\Desktop\Sample Pictures\Penguins.jpg');
% figure, imshow(f);
% A=rgb2gray(f);
% figure, imshow(A);
A=imread('C:\Users\Marjan\Desktop\Sample Pictures\Penguins.jpg');
B0=bitget(A,1); figure, imshow(logical(B0));title('Bit plane 1');
B1=bitget(A,2); figure, imshow(logical(B1));title('Bit plane 2');
B2=bitget(A,3); figure, imshow(logical(B2));title('Bit plane 3');
B3=bitget(A,4); figure, imshow(logical(B3));title('Bit plane 4');
B4=bitget(A,5); figure, imshow(logical(B4));title('Bit plane 5');
B5=bitget(A,6); figure, imshow(logical(B5));title('Bit plane 6');
B6=bitget(A,7); figure, imshow(logical(B6));title('Bit plane 7');
B7=bitget(A,8); figure, imshow(logical(B7));title('Bit plane 8');
