I=imread('C:\Users\Marjan\Documents\MATLAB\Marjan.jpg');
f=rgb2gray(I);
[M,N]=size(f);
F=fft2(double(f));
u=0:(M-1);
v=0:(N-1);
idx=find(u>M/2);
u(idx)=u(idx)-M;
idy=find(v>N/2);
v(idy)=v(idy)-N;
[V,U]=meshgrid(v,u);
D=sqrt(U.^2+V.^2);
P=30;
H=double(D>=P);
G=H.*F;
g=real(ifft2(double(G)));
figure,imshow(f),title('orginal image');figure,imshow(g,[ ]);title('filtered image with Ideal high pass');
G=(1-H).*F;
g=real(ifft2(double(G)));
figure,imshow(g,[ ]);title('filtered image with Ideal low pass');
B=(1-H).*H;
G=B.*F;
g=real(ifft2(double(G)));
figure,imshow(g,[ ]);title('filtered image with Ideal band pass');
G=(1-B).*F;
g=real(ifft2(double(G)));
figure,imshow(g,[ ]);title('filtered image with Ideal band stop');